
const productos =[
    {
        "id": 1,
        "producto": "anillo",
        "img": "imagenes/amethys.jpg",
        "precio": 47000,
        "descripcion": "anillo diamante",
        "oferta": true,
    },
    { 
        "id": 2,
        "producto": "collar",
        "img": "imagenes/collar.jpg",
        "precio": 7000,
        "descripcion": "collar con perlas",
        "oferta": false,
    },
    { 
        "id":3,  
        "producto": "colgante",
        "img": "imagenes/collarheart.jpg",
        "precio": 9000,
        "descripcion": "colgante con forma de corazon",
        "oferta": true,
    },
    { 
        "id": 4,
        "producto":"pulsera",
        "img": "imagenes/pulsera.jpg",
        "precio": 5500,
        "descripcion": "pulsera de oro",
        "oferta": false,
    },
    { "id":5,
        "producto": "reloj",
        "img": "imagenes/reloj.jpg",
        "precio": 6500,
        "descripcion": "reloj de bolsillo",
        "oferta": false,
    },
    {   
        "id":6,
        "producto":"aros",
        "img": "imagenes/aros.jpg",
        "precio": 7500,
        "descripcion": "aros redondos",
        "oferta": false,
    },
    { "id":7,
        "producto":"alianzas oro",
        "img": "imagenes/anillos.jpg",
        "precio": 45000,
        "descripcion":"alianzas oro 18 kilates",
        "oferta":false,
    },
    { "id":8,
        "producto":"alianzas plata",
        "img": "imagenes/alianzasplata.jpg",
        "precio": 14000,
        "descripcion":"alianzas de plata 825",
        "oferta": false,
    },
    {   "id":9,
        "producto":"colgante",
        "img": "imagenes/colgante.jpg",
        "precio": 6990,
        "descripcion":"colgante corazon",
        "oferta":false,
    },
    { "id":10,
        "producto":"anillo boda",
        "img": "imagenes/anilloboda.jpg",
        "precio": 48000,
        "descripcion":"anillo casamiento dama",
        "oferta":false,
    },
]
